### PR TITLE
Segments, predicates, chain request/response

### LINKED ISSUE #20: Have an implicit`{__REQUEST_URI_AFTER_PREFIX__}` at the end of the origin URI, if its not specified in the PREFIX mode.
Currently, in the `PREFIX` mode, you need to specify in the URI variable`{__REQUEST_URI_AFTER_PREFIX__}`. But in many cases this variable will be placed at the end of the Origin's path. So why not just put it implicitly at the end of the origin's path.

So something like this:
| ROUTE | ORIGIN URI | ORIGIN URI AFTER|
|--------|-------------|-----------------|
| `/api/*` |  `my.site.tld` | `my.site.tld/{__REQUEST_URI_AFTER_PREFIX__}`|
| `/api/*` |  `my.site.tld/{__REQUEST_URI_AFTER_PREFIX__}` | `my.site.tld/{__REQUEST_URI_AFTER_PREFIX__}`|
| `/api/*` |  `my.site.tld/a/{__REQUEST_URI_AFTER_PREFIX__}/b` | `my.site.tld/a/{__REQUEST_URI_AFTER_PREFIX__}/b`|
| `/api/*` |  `my.site.tld?uri={__REQUEST_URI_AFTER_PREFIX__}?flag=true` | `my.site.tld?uri={__REQUEST_URI_AFTER_PREFIX__}?flag=true`|

### LINKED ISSUE #24: `PathMode` reworking and segment handling
While researching the current routing mechanisms, it became clear that the existing API contains several edge cases and can be confusing to configure. This proposal introduces a more robust, less error-prone solution divided into two main areas: **Path Definition** and **UriTemplate Expansion**.

## 1. Path Definition and Modes

Currently, routes are defined using either `Router#route(String path)` or `Router#routeWithRegex(String regex)`. These act as high-level predicates checking the requested path at the edge service. 

### The Current State (Old Path Modes)

We currently utilize four distinct path modes:

| Mode | Description |
| :--- | :--- |
| **FIXED** | Requires a 1:1 exact match of the actual request path. |
| **PREFIX** | Similar to FIXED, but sets a `UriTemplate` variable (`{__REQUEST_URI_AFTER_PREFIX__}`) for the path after the wildcard. |
| **PARAMS** | Allows segments (regex and non-regex) to extract values from the request URI into `UriTemplate` variables. |
| **REGEXP** | The most flexible mode, allowing users to define paths explicitly via regular expressions. |

### Issues with the Current Approach

1. **The `.*` in PARAMS:** Non-regex params (e.g., `/my/{something}/path`) currently translate to `/my/.*/path`. This is a incorrect because `.*` greedily consumes path separators. A request to `/my/a/b/path` would incorrectly match, assigning `a/b` to the variable. This must be changed to `[^/]+` to strictly match a single segment.
2. **Non-Standard Regex Syntax:** Our current custom syntax `{<NAME>REGEXP}` is functional but unconventional.

### The Jakarta REST Path Standard and the `BASIC` Mode

To align with standards, we should adopt the Jakarta REST Path specification format: `{NAME:REGEXP}`. Since Quarkus almost supports Jakarta REST specification, this format will be immediately familiar to developers.

Furthermore, `FIXED`, `PREFIX`, and `PARAMS` share so much overlapping behavior that they should be consolidated into a single mode.

#### Proposed PathMode enum
```java
enum PathMode {
    BASIC,   // A unified mode replacing FIXED, PREFIX, and PARAMS, set by Default
    REGEXP   // Explicit, bulletproof regex mode (similar to Spring Cloud Gateway).
}
```

#### Basic mode
`BASIC` mode will automatically transform human-readable paths into strict regex patterns under the hood. 

```java
// Example Transformation
String originalPath = "/hello/./{a}/{b:[a-z]+}/*";

// Transforms into:
// "^/hello/\./(?<a>[^/]+)/(?<b>[a-z]+)(?:/(?<__REQUEST_URI_AFTER_PREFIX__>.*))?$"
String transformedPath = Utils.transform(originalPath); 

router.routeWithRegex(transformedPath);
```

> [!NOTE] 
> In `BASIC` mode, `*` acts strictly as a wildcard. If a user needs an actual, literal asterisk in their path, they must use the `REGEXP` mode.

#### Backreferences support
Currently, defining two segments with the same name throws an exception. We can introduce a feature that leverages regex backreferences (`\k<NAME>`) to enforce 1:1 matching between segments. 

If a user defines `/my/{a:[a-z]+}/{a:[a-z]+}/path`, the edgy will translate the second identical identifier into a backreference: `/my/(?<a>[a-z]+)/\k<a>/path`. If the segments share the same name but have conflicting regex definitions, the edgy will throw a clear validation exception during setup.

---

## 2. Segment Expansion and URI Templates

Once a request is successfully routed, it is redirected via a reverse proxy to an origin URI. Values extracted from the matched path must be injected into the origin's `UriTemplate`.

#### Variables Injected into the Template:
* Extracted regex groups
* The trailing wildcard group (`{__REQUEST_URI_AFTER_PREFIX__}`) - special case of extracted regex groups
* **Decoded** query parameters
* The origin URI (`{__REQUEST_URI__}`)

### The Double-Encoding Bug
Request URIs are URL-encoded by default. When we extract a segment, it remains encoded. If we pass this extracted value into `UriTemplate#expandToString()`, the template will encode it *again*, destroying the data (e.g., a `%20` becomes `%2520`). This is especially "destructive" for wildcard groups containing `/` characters.

### Reserved Expansions
`UriTemplate` supports the `+` operator (e.g., `{+path}`), which explicitly tells the template engine *not* to URL-encode the injected value. https://vertx.io/docs/4.5.25/vertx-uri-template/java/#_reserved_expansion

So one solution I came up with is to encourage developers to write clean origin URIs like `/my/{path}/{to}/origin` but under the hood, the system will automatically map these to `/my/{+path}/{+to}/origin` to bypass the destructive double-encoding.

While this means we forfeit some advanced `UriTemplate` features (like form-style query continuations), it guarantees the integrity of the routed data.

### Implicit Wildcard Appending

Currently, developers must explicitly append `{__REQUEST_URI_AFTER_PREFIX__}` to their origin URIs, which is highly unintuitive. 

Ideally, the edgy should automatically append `{__REQUEST_URI_AFTER_PREFIX__}` to the origin URI if the variable exists in the matched path but is missing from the provided origin template.

___
Edit:I think there could be some further optimization if the path does **not** contain any sections (`{segment}`/`{segment:.*}`) or any wildcards (`*`) -- only `router.route(path)` can be used, so there is no need for the transformation.

### PR DESCRIPTION
**Pull request by mskacelik**
fixes #20 #19
closes #24 

Finally was able to code this beast of a PR :) (with bit of a help of 🤖)
Few notes:
 - `PathMode` = `BASIC`, `REGEXP`
 - segments are now handled as described in the #24
 - segment names have to be in pattern of `[a-zA-Z][a-zA-Z0-9]*` this is because how `java.util.regex.Pattern` works.
     - because of that I needed to change the `__REQUEST_URI__` and `__REQUEST_URI_AFTER_PREFIX__` => `requestURI` and `suffix`.
     - Jakarta REST uses something bit different, it actually bypasses the Java Regex's naming "limitation", but for 
         - a) they don't have full RegExp support for `@Path`s unlike "we" do.
         - b) I think it would introduce a more complex solution then it already is
       So I think its fine as it is, at least for now.
 - also changed the predicate API => I don't think it really make sense for having a list of predicates, you can just simply use `||`/`&&` instead.
 - reverted the order of the `Response Transformers`, it was bit confusing for the user (i.e.  me :)).
 - also fixed a "bug" (that was previously a feature ;) ) that now enables rest of the response transformer chain to be executed when `ErrorProxyResponse` is built.
    - obviously, request transformer chain is skipped, since it does not make sense to continue the chain when error happens (and the `ErrorProxyResponse` is returned instead).
    - idea behind this, is that this can be later used for observation interceptors feature (metrics, traces).

### CODE REVIEW

**Comment by mskacelik** [comment]
I just noticed that the JDK25 has ton of ERROR logs, yet it passed...
Is this known issue?

**Comment by mskacelik** [comment]
Added new 3 commits, that are pretty much:
- refactoring the configuration applying for the HttpClient (origin based config) - using a seperate Manager class (SOLID principles etc..., you get it...)
- added `idleTimeout` and `maxPoolSize` config properties for http client (I suspect that Quarkus has its own global properties for http clients).
- additional refactoring of the interceptors (not the request/response transformers) - once again some SOLID principles shenanigans.

Idea for these three commits is to make the `RouteConfigurator` as small as possible.

**Comment by mskacelik** [comment]
> I just noticed that the JDK25 has ton of ERROR logs, yet it passed... Is this known issue?

This seems to have been fixed in newer versions of Quarkus. I added an additional three bump commits. This should obviously be done with Dependabot, but I don't think it's worth setting up Dependabot maintenance before transferring the project to Quarkiverse :).

**Comment by jponge** [comment]
I'm running this PR with Temurin 25 and I'm not seeing any error. What are these?

**Comment by mskacelik** [comment]
> I'm running this PR with Temurin 25 and I'm not seeing any error. What are these?

It was some issue with Quarkus 3.31.0 (atleast):
```
Exception in thread "vert.x-internal-blocking-1" java.lang.IllegalAccessError: module java.base does not open java.lang to unnamed module @35a2a66f; to use the thread-local-reset capability on Java 24 or later, use this JVM option: --add-opens java.base/java.lang=ALL-UNNAMED
	at org.jboss.threads.JDKSpecific$ThreadAccess.<clinit>(JDKSpecific.java:32)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:13)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1474)
Exception in thread "executor-thread-1" java.lang.NoClassDefFoundError: Could not initialize class org.jboss.threads.JDKSpecific$ThreadAccess
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:13)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalAccessError: module java.base does not open java.lang to unnamed module @35a2a66f; to use the thread-local-reset capability on Java 24 or later, use this JVM option: --add-opens java.base/java.lang=ALL-UNNAMED [in thread "vert.x-internal-blocking-1"]
	at org.jboss.threads.JDKSpecific$ThreadAccess.<clinit>(JDKSpecific.java:32)
	... 3 more
```
The error is not present in the newer version of Quarkus. Also, it did not have any effect on the test case.
Probably something related to: https://github.com/quarkusio/quarkus/discussions/51041?

**Comment by jponge** [comment]
Yes you can ignore these

**Review by jponge — APPROVED** [review]
Looks good to me :-)

File: runtime/src/main/java/org/acme/edgy/runtime/RouterConfigurator.java [hunk 1]
```diff
@@ -211,7 +211,7 @@ public Future<ProxyResponse> handleProxyRequest(ProxyContext context) {
         });
     }
 
-    private void applyRequestTransformers(List<RequestTransformer> requestTransformers, HttpProxy proxy) {
+    private void applyRequestTransformers(Collection<RequestTransformer> requestTransformers, HttpProxy proxy) {
```
Comment (tsegismont) [inline runtime/src/main/java/org/acme/edgy/runtime/RouterConfigurator.java]: Why did you change from `List` to `Collection`? Applying a `Set` of transformers wouldn't be a great idea, because you most certainly to preserve the order of definition

**Review by tsegismont — COMMENTED** [review]
Overall, looks good to me. But I'm not sure about one API change

File: runtime/src/main/java/org/acme/edgy/runtime/RouterConfigurator.java (hunk 1 above)
Comment (mskacelik) [reply runtime/src/main/java/org/acme/edgy/runtime/RouterConfigurator.java]: Oh yes, I actually wanted to use most common "ancestor/abstraction" for `ArrayDeque` and `ArrayList` - for the sake of consistency, but I agree. Actually the code that you highlighted was removed in one of the most recent commits, with that said, I will use `List<K>` and `Deque<K>` respectively in the `Router.class` getters/fields.
