### PR TITLE
SmallRye Fault Tolerance integration

### LINKED ISSUE #9: Implement Circuite Breaker Request Transformers
https://vertx.io/docs/4.5.22/vertx-circuit-breaker/java/

WIP branch: https://github.com/mskacelik/edgy/tree/circuit-breaker-transformer – retry does not work

Still thinking about if passing `CircuitBreaker` instance is sufficient enough, because of `fallback` method, but I guess we can solve that with more convenient way of handling fallback requests (something like a factory method for http client and request on fly).

### PR DESCRIPTION
**Pull request by mskacelik**
This PR introduces core **SmallRye Fault Tolerance (SR-FT)** patterns to the API Gateway.
Closes #9 

### Implemented Features
* **Circuit Breaker**
* **Timeout**
* **Bulkhead**
* **RateLimit**
* **Fallback**
---

#### 1. Retry
The `Retry` mechanism is currently missing due to the design of the reverse proxy. Because the current architecture requires `sendRequest()` to be called exactly once, implementing retries is not as straightforward as other features. 

#### ~2. Fallback~
~Implementation is pending a decision on the desired fallback strategy. Potential options from my side are:~
*~**A) Custom Response**: Returning a mocked response.~
*~**B) Redirection**: Forwarding the request to an alternative URI (e.g., a secondary microservice or a local custom endpoint).~

~FT's `withFallback().handle(() -> ...)` method requires a supplier returning `Future<ProxyResponse>`, which is cumbersome with our existing API.~ We likely need a **custom Adapter API** to simplify Fault Tolerance integration for this project. This also includes API that is not relevant for this project (i.e., `enableSynchronousQueueing` (?)) and the API that might be relevant to our project (i.e., expectations).

### Additional Changes
Refactored the integration tests to use a single API Gateway instance for all communication.

### CODE REVIEW

**Comment by mskacelik** [comment]
> I'm no expert, but this seems reasonable. I'm not sure why fallback handler requiring the same type as the operation is weird to you, because that lets you recover a failed request with another request, which seems like something you should be able to do. Retries are indeed weird because relatively often, a failure will invalidate some parts of a shared context and blindly invoking the guarded code again will just not make any sense. But I don't think that can be solved on the SRye FT level (at least we have before retry handlers, but I'm not sure they can fix everything...).

Thanks for the input, @Ladicek. Perhaps I explained the problem with `withFallback` incorrectly. The issue was that there was no straightforward way to obtain a `Future<ProxyResponse>` because you need a `ProxyContext` object, which is only available in the transformers' `apply` method.

That said, I think I found a possible solution and came up with this API.
```java
.addRequestTransformer(
    new RequestFaultToleranceApplier((proxyContext, builder) -> builder
        .withFallback().handler(() -> {
            ProxyResponse fallbackResponse = proxyContext.request().release().response()
                  setBody(Body.body(Buffer.buffer("Fallback response")))setStatusCode(OK);
            return Future.succeededFuture(fallbackResponse);
            }).done())));
```
Implementing it in the Transformer was quite tricky. You can look at the comments for my explanations. But at least we have that out of the way.

That said, `testBulkhead` seems a bit flaky. It seems to fail more often in native mode, but it has failed a few times in JVM mode too, both in GH actions and locally, though rarely. I will investigate this, but I welcome some proofreading of the tests.

Also, since Quarkus 3.31.CR1 was released, I will undraft this PR. @jponge @tsegismont

**Comment by mskacelik** [comment]
> The easiest way here is to make sure the server code, whose call is guarded by the concurrency limiter, takes a long time, say 5 seconds. There's still potential for races, but 5 seconds should be relatively safe.

Oh, yes. You were right -- tho it was kinda obvious. That seems to have done the trick. I set it to one second. Hopefully, that will be enough. I don't want to "extend" the already lengthy tests any further.

> and the server is actually also a client to another server?

I guess you can say that ;)

File: integration-tests/src/main/java/org/acme/edgy/it/faulttolerance/FaultToleranceResourceApi.java [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+        // 11-12 succeeds
+        // 13 fails
+        // ==== CB OPEN ====
+        // ... does not increment the counter ...
+        // ... after delay period ...
+        // ==== CB HALF-OPEN ====
+        // 14-16 succeeds
+        // ==== CB CLOSED ====
+        // 16-21 succeeds
+        switch (circuiteBreakerInvocationCounter.incrementAndGet()) {
```
Comment (jponge) [inline integration-tests/src/main/java/org/acme/edgy/it/faulttolerance/FaultToleranceResourceApi.java]: 👍

Comment (jponge) [reply integration-tests/src/main/java/org/acme/edgy/it/faulttolerance/FaultToleranceResourceApi.java]: ... but you should rename to `circuitBreakerInvocationCounter` (without the `e` 😄 )
